services:
  backend:
    build: ./backend
    container_name: asterflow-backend
    restart: always
    # Point to the root .env file automatically
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mysql+mysqlconnector://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - AMI_HOST=${AMI_HOST}
      - AMI_PORT=${AMI_PORT}
      - AMI_USER=${AMI_USER}
      - AMI_PASS=${AMI_PASS}
      - TABLE_NAMES=${TABLE_NAMES}
      - RECORDINGS_PATH=/var/spool/asterisk/monitor
    volumes:
      - /var/spool/asterisk/monitor:/var/spool/asterisk/monitor
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend_v3
    container_name: asterflow-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_ASTERISK_IP=${VITE_ASTERISK_IP}
    ports:
      - "80:80"
